### ISSUE TITLE
windows Socket timeout reached

### ISSUE THREAD

**Issue by Linqh1215** [EvilFreelancer/routeros-api-php#112] opened 2024-03-01 10:30 UTC
Display Socket timeout reached during Windows development process

**Comment by 1260545050** [comment] 2024-03-01 10:47
Error message ： Unable to establish socket session，How does the solve it?

**Comment by EvilFreelancer** [comment] 2024-03-11 06:56
Hi! Your issue is probably a duplicate of #111

**Comment by nestinho** [comment] 2024-04-02 14:43
"Unable to establish socket session, A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."

On regard to this kind of question, i am also getting similar thing latest.

**Comment by EvilFreelancer** [comment] 2024-05-30 17:24
Hi! This mean router is unavailable from the side where you make a library call.

**Closed by EvilFreelancer** 2024-05-30 17:24 UTC
Labels: question
